---
# Install unattended-upgrades
- name: Install unattended-upgrades
  become: true
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true

# Configure unattended-upgrades
- name: Configure unattended-upgrades
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
